User.create(name: 'Paolo', email: 'paolo.guglielmini.vr@gmail.com')
User.create(name: 'Flavia', email: 'flavia.veronese901@gmail.com')
User.create(name: 'Alberto', email: 'paoloalbert@alice.it')
Cinema.create(name: 'UCI Cinemas Verona', address: 'Via Monte Amiata, 37057 San Giovanni Lupatoto VR', webpage: 'http://www.ucicinemas.it/generic/rassegne.php', promotion_name: 'Ricomincio da tre', promotion_desc: 'Tutti i martedì film a 3 euro', enabled: true)
Cinema.create(name: 'Multisala Rivoli', address: 'Piazza Brà, 10, 37121 Verona VR', webpage: 'http://www.multisalarivoli.it/film/index_settdata.php?idcinema=1491&visual=b', promotion_name: '2x1 Facebook', promotion_desc: 'Stampando la promo facebook il giovedì entrano due al prezzo di uno', enabled: true)
Cinema.create(name: 'Cinema Fiume', address: 'Vicolo Cere, 14', webpage: 'http://www.cinemafiume.it/cinema-fiume', promotion_name: 'Mercoledì ingresso 4.5€', promotion_desc: 'Il mercoledì ingresso scontato a 4.5 euro', enabled: true)
Cinema.create(name: 'Cinema Kappadue', address: 'Via Antonio Rosmini, 1, 37123 Verona VR', webpage: 'http://www.cinemafiume.it/cinema-kappadue', promotion_name: 'Mercoledì ingresso 4.5€', promotion_desc: 'Il mercoledì ingresso scontato a 4.5 euro', enabled: true)
Cinema.create(name: 'Cinema Diamante', address: 'Via Pietro Zecchinato, 5, 37136 Verona VR', webpage: 'http://www.cinemafiume.it/cinema-diamante', promotion_name: 'Mercoledì ingresso 4.5€', promotion_desc: 'Il mercoledì ingresso scontato a 4.5 euro', enabled: true)
Cinema.create(name: 'Cinema Pindemonte', address: 'Via Sabotino, 2/b, 37124 Verona VR', webpage: 'http://www.cinemafiume.it/cinema-pindemonte', promotion_name: 'Mercoledì ingresso 4.5€', promotion_desc: 'Il mercoledì ingresso scontato a 4.5 euro', enabled: true)
